# Generated by Django 3.2.7 on 2021-10-11 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='signed_issuer',
            field=models.BooleanField(default=False, help_text='1 : Issuer has signed with BankID'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='signed_obligor',
            field=models.BooleanField(default=False, help_text='1 : Obligor has signed with BankID'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='amortisation',
            field=models.BooleanField(help_text='1 translates into linear amortisation'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='perpetual',
            field=models.BooleanField(help_text='1 translates into a perpetual agreement (no end-date)'),
        ),
    ]
